### ISSUE TITLE
Manual de Identidad

### ISSUE THREAD

**Issue by BelenPascual** [city-chip/press-kit#2]
Manual de identidad con los siguientes apartados:
- [X] Logotipo corporativo (falta que me lo envíen vectorizado)
- [X] Área de Seguridad y Reductibilidad 
- [X] Colores corporativos
- [X] Tipografía corporativa (y secundaria en caso de necesidad)
- [X] Normas para el buen uso de la marca
- [X ] Versiones correctas y aplicaciones correctas
- [X] Versiones incorrectas y aplicaciones incorrectas correctas
- [X] Aplicaciones de marca
- [X ] Papelería corporativa y tarjeta visita
Manual elaborado con el programa InDesign
https://github.com/city-chip/press-kit/tree/main/Manual%20identidad/Manual%20identidad%20empaquetado

**Comment by BelenPascual** [comment]
@ajsb85 Hola Alexander, acabo de subir una nueva versión del Manual de identidad visual de CityChip. Sigue siendo un borrador porque el contenido no está completo aún, aunque está avanzado. Todavía tengo que mejorarlo y sobre todo unificar formatos y "ponerlo bonito".  https://github.com/city-chip/press-kit/blob/main/Manual%20identidad.pdf

**Comment by ajsb85** [comment]
Hola  @BelenPascual 

Recuerda crear el checklist en la descripción de esta tarea.
Y el enlace hacia el manual de identidad está roto. Hay que actualizarlo a la nueva ubicación.

Saludos.

**Comment by BelenPascual** [comment]
Ahora lo hago, gracias!

**Comment by ajsb85** [comment]
Hola @BelenPascual 

Un encabezado tan oscuro en un documento que se imprime puede ser costoso para imprimir.

![Image](https://github.com/city-chip/press-kit/assets/663460/01b44e27-895a-487e-b0d9-f08b4727f14f)

**Comment by BelenPascual** [comment]
@ajsb85,he escuchado tu audio y comentabas de vectorizar el logo. Eso puede suponer bastante rato, básicamente en lo que hace referencia a la "C", que es complicada. Creo sería más productivo que te lo enviasen ellos. En el diseño del manual y tarjeta de presentación puedo dejar el logotipo que actualmente ya tenemos y cuando te envíen el correcto, sólo habría que sustituirlo. Ya me dirás. Gracias!

**Comment by ajsb85** [comment]
Vale. No te preocupes. Lo pongo de tarea para el grupo siguiente. Ayúdanos en el ámbito que mejor sabes hacer. Bona nit!

**Comment by BelenPascual** [comment]
@ajsb85 , en cuanto al logo de Citychip, he creado uno de manera provisional ( que no es igual al original) porque el que adjuntaba en los distintos documentos da incompatibilidad con el negro que estaba usando. De ahí la diferencia de tonalidades de negro entre el logo y los cuadrados negros. Hoy ya lo he sustituido en algunos documentos. Mañana lo sustituyo en el resto.
