### ISSUE TITLE
Datasheet product

### ISSUE THREAD

**Issue by BelenPascual** [city-chip/press-kit#3]
Realizar diseño
Añadir contenido
https://github.com/city-chip/press-kit/tree/main/Datasheet

**Comment by BelenPascual** [comment]
@ajsb85 Hola Alexander, ya dirás si con el diseño del Datasheet voy bien encaminada, gracias!

**Comment by ajsb85** [comment]
Hola @BelenPascual 

¿Puedes mantener un solo color en este encabezado?


![Screenshot_2023-11-15-18-17-50-036_com.github.android-edit.jpg](https://github.com/city-chip/press-kit/assets/663460/e4517361-f6c4-4845-93a6-6431b717d34f)
